version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.0.0
    container_name: kd
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./keycloak/realm.json:/opt/keycloak/data/import/realm.json
      - ./keycloak/themes/kd:/opt/keycloak/themes/k-demo
    command: ["start-dev", "--import-realm"]
